"""Generate loreserver auth overlay TOML from this machine's MagicDNS name."""

from __future__ import annotations

from pathlib import Path


def build_loreserver_auth_toml(
    *,
    dns_name: str,
    grpc_port: int = 50051,
    http_port: int = 8443,
) -> str:
    """dns_name e.g. alice.tailXXXX.ts.net — never hardcode a student hostname."""
    dns = dns_name.rstrip(".")
    issuer = f"https://{dns}"
    return (
        "# Generated by lore-auth menu — include/merge into loreserver config, then restart loreserver.\n"
        "# Do not hand-edit hostnames; re-run Setup authentication server to regenerate.\n"
        "\n"
        "[environment.endpoint]\n"
        f'auth_url = "ucs-auth://{dns}:{grpc_port}"\n'
        "\n"
        "[server.auth]\n"
        f'jwt_issuer = "{issuer}"\n'
        f'jwt_audience = ["{dns}"]\n'
        "\n"
        "[server.auth.jwk]\n"
        f'endpoint = "{issuer}:{http_port}/.well-known/jwks.json"\n'
    )


def write_loreserver_auth_toml(
    out_path: Path,
    *,
    dns_name: str,
    grpc_port: int = 50051,
    http_port: int = 8443,
) -> Path:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    text = build_loreserver_auth_toml(
        dns_name=dns_name, grpc_port=grpc_port, http_port=http_port
    )
    out_path.write_text(text, encoding="utf-8")
    return out_path
