"""Generate Lore Server authentication configuration."""
from __future__ import annotations
from pathlib import Path


def build_loreserver_auth_toml(*, dns_name: str, audiences: list[str] | None = None, grpc_port: int = 50051, http_port: int = 8443) -> str:
    dns = dns_name.rstrip(".")
    issuer = f"https://{dns}"
    values = list(dict.fromkeys([dns, *(audiences or [])]))
    audience_toml = ", ".join(f'"{value}"' for value in values)
    return (
        "# Generated by lore-auth menu. Do not edit by hand.\n\n"
        "[environment.endpoint]\n"
        f'auth_url = "ucs-auth://{dns}:{grpc_port}"\n\n'
        "[server.auth]\n"
        f'jwt_issuer = "{issuer}"\n'
        f"jwt_audience = [{audience_toml}]\n\n"
        "[server.auth.jwk]\n"
        f'endpoint = "{issuer}:{http_port}/.well-known/jwks.json"\n'
    )


def write_loreserver_auth_toml(out_path: Path, *, dns_name: str, audiences: list[str] | None = None, grpc_port: int = 50051, http_port: int = 8443) -> Path:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(build_loreserver_auth_toml(dns_name=dns_name, audiences=audiences, grpc_port=grpc_port, http_port=http_port), encoding="utf-8")
    return out_path
